// Export all feature components
export * from "./assignments";
export * from "./auth";
export * from "./avatar";
export * from "./charts";
export * from "./course";
export * from "./currency";
export * from "./dashboard";
export * from "./editor";
export * from "./gamification";
export * from "./learning";
export * from "./navigation";
export * from "./profile";
export * from "./quiz";
export * from "./shared";
export * from "./shop";
export * from "./admin";
export * from "./grade-management";
export * from "./ai-tutor";
